---
sidebar: sidebar 
permalink: concept-client-protocols.html 
keywords: client protocols, client version, smb version, nfs version, protocol versions, s3, smb, nfs, iscsi, cifs 
summary: Cloud Volumes ONTAP unterstützt iSCSI-, NFS-, SMB- und S3-Client-Protokolle. 
---
= Client-Protokolle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP unterstützt iSCSI-, NFS-, SMB- und S3-Client-Protokolle.



== ISCSI

ISCSI ist ein Blockprotokoll, das in standardmäßigen Ethernet-Netzwerken ausgeführt werden kann. Die meisten Client-Betriebssysteme bieten einen Software-Initiator, der über einen Standard-Ethernet-Port ausgeführt wird.



== NFS

NFS ist das herkömmliche File-Zugriffsprotokoll für UNIX- und LINUX-Systeme. Clients können über die Protokolle NFSv3, NFSv4 und NFSv4.1 auf Dateien in ONTAP Volumes zugreifen. Sie können den Dateizugriff mithilfe von UNIX-Berechtigungen, NTFS-Berechtigungen oder einer Kombination beider Berechtigungen steuern.

Clients können sowohl über NFS- als auch SMB-Protokolle auf dieselben Dateien zugreifen.



== SMB

SMB ist das herkömmliche File-Zugriffsprotokoll für Windows-Systeme. Die Clients können über die Protokolle SMB 2.0, SMB 2.1, SMB 3.0 und SMB 3.1.1 auf Dateien in ONTAP Volumes zugreifen. Wie bei NFS werden auch hier verschiedene Berechtigungsstile unterstützt.

ifdef::aws[]

endif::aws[]

ifdef::azure[]

endif::azure[]
