---
settings:
  name: Cloud Volumes ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Cloud-Provider
    default: Alle Cloud-Provider
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: Cloud Volumes ONTAP Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/reference-limitations.html"
    - title: Versionshinweise zu Cloud Volumes ONTAP
      url: "/whats-new-ontap.html"
  - title: Los geht's
    entries:
    - title: Weitere Informationen zu Cloud Volumes ONTAP
      url: "/concept-overview-cvo.html"
    - title: Unterstützte Versionen für neue Bereitstellungen
      url: "/reference-versions.html"
    - title: Erste Schritte in Amazon Web Services
      flavor: aws
      entries:
      - title: Schnellstart
        url: "/task-getting-started-aws.html"
      - title: Planen Sie Ihre Konfiguration
        url: "/task-planning-your-config.html"
      - title: Richten Sie Ihr Netzwerk ein
        entries:
        - title: Netzwerkanforderungen
          url: "/reference-networking-aws.html"
        - title: AWS Transit Gateway einrichten
          url: "/task-setting-up-transit-gateway.html"
        - title: Implementieren Sie ein HA-Paar in einem gemeinsamen Subnetz
          url: "/task-deploy-aws-shared-vpc.html"
        - title: Sicherheitsgruppenregeln für AWS
          url: "/reference-security-groups.html"
      - title: AWS KMS einrichten
        url: "/task-setting-up-kms.html"
      - title: Einrichten von IAM-Rollen
        url: "/task-set-up-iam-roles.html"
      - title: Lizenzierung einrichten
        url: "/task-set-up-licensing-aws.html"
      - title: Starten Sie Cloud Volumes ONTAP in AWS
        url: "/task-deploying-otc-aws.html"
      - title: Erste Schritte in AWS C2S
        url: "/task-getting-started-aws-c2s.html"
    - title: Erste Schritte in Microsoft Azure
      flavor: azure
      entries:
      - title: Schnellstart
        url: "/task-getting-started-azure.html"
      - title: Planen Sie Ihre Konfiguration
        url: "/task-planning-your-config-azure.html"
      - title: Richten Sie Ihr Netzwerk ein
        url: "/reference-networking-azure.html"
      - title: Richten Sie die Verschlüsselung mit Ihrem Schlüssel ein
        url: "/task-set-up-azure-encryption.html"
      - title: Lizenzierung einrichten
        url: "/task-set-up-licensing-azure.html"
      - title: Aktivieren Sie den Hochverfügbarkeits-Modus
        url: "/task-azure-high-availability-mode.html"
      - title: Starten Sie Cloud Volumes ONTAP in Azure
        url: "/task-deploying-otc-azure.html"
    - title: Erste Schritte in Google Cloud
      flavor: gcp
      entries:
      - title: Schnellstart
        url: "/task-getting-started-gcp.html"
      - title: Planen Sie Ihre Konfiguration
        url: "/task-planning-your-config-gcp.html"
      - title: Richten Sie Ihr Netzwerk ein
        url: "/reference-networking-gcp.html"
      - title: Planung von VPC Service-Kontrollen
        url: "/reference-vpc-service-controls-gcp.html"
      - title: Erstellen eines Dienstkontos
        url: "/task-creating-gcp-service-account.html"
      - title: Nutzen Sie vom Kunden verwaltete Schlüssel
        url: "/task-setting-up-gcp-encryption.html"
      - title: Lizenzierung einrichten
        url: "/task-set-up-licensing-google.html"
      - title: Starten Sie Cloud Volumes ONTAP in Google Cloud
        url: "/task-deploying-gcp.html"
  - title: Verwenden Sie Cloud Volumes ONTAP
    entries:
    - title: Lizenzmanagement
      entries:
      - title: Management kapazitätsbasierter Lizenzen
        url: "/task-manage-capacity-licenses.html"
      - title: Managen Sie Keystone Flex-Abonnements
        url: "/task-manage-keystone.html"
      - title: Management knotenbasierter Lizenzen
        url: "/task-manage-node-licenses.html"
    - title: Volume- und LUN-Administration
      entries:
      - title: Volumes erstellen
        url: "/task-create-volumes.html"
      - title: Management vorhandener Volumes
        url: "/task-manage-volumes.html"
      - title: Tiering inaktiver Daten in Objektspeicher
        url: "/task-tiering.html"
      - title: Verbinden Sie eine LUN mit einem Host
        url: "/task-connect-lun.html"
      - title: Beschleunigter Datenzugriff mit FlexCache
        url: "/task-accelerate-data-access.html"
    - title: Aggregatadministration
      entries:
      - title: Erstellen von Aggregaten
        url: "/task-create-aggregates.html"
      - title: Management vorhandener Aggregate
        url: "/task-manage-aggregates.html"
      - title: Managen von Kapazitätseinstellungen
        url: "/task-manage-capacity-settings.html"
    - title: Storage VM-Administration
      entries:
      - title: Arbeiten Sie mit Storage VMs in BlueXP
        url: "/task-managing-svms.html"
      - title: Erstellung von Storage VMs in AWS
        flavor: aws
        url: "/task-managing-svms-aws.html"
      - title: Erstellung von Storage VMs in Azure
        flavor: azure
        url: "/task-managing-svms-azure.html"
      - title: Erstellung von Storage VMs in Google Cloud
        flavor: gcp
        url: "/task-managing-svms-gcp.html"
    - title: Sicherheit und Datenverschlüsselung
      entries:
      - title: Verschlüsselung von Volumes mit NetApp Verschlüsselung
        url: "/task-encrypting-volumes.html"
      - title: Verschlüsselungsmanagement mit Azure Key Vault
        flavor: azure
        url: "/task-azure-key-vault.html"
      - title: Verwalten von Schlüsseln mit Google Cloud KMS
        flavor: gcp
        url: "/task-google-key-manager.html"
      - title: Ransomware-Schutz verbessern
        url: "/task-protecting-ransomware.html"
    - title: Systemadministration
      entries:
      - title: Upgrade von Cloud Volumes ONTAP
        url: "/task-updating-ontap-cloud.html"
      - title: "„Pay-as-you-go“-Systeme registrieren"
        url: "/task-registering.html"
      - title: Stoppen und starten Sie ein System
        url: "/task-managing-state.html"
      - title: Systemzeit synchronisieren
        url: "/task-sync-time.html"
      - title: Ändern Sie die Schreibgeschwindigkeit des Systems
        url: "/task-modify-write-speed.html"
      - title: Ändern Sie das Systemkennwort
        url: "/task-change-password.html"
      - title: Hinzufügen, Entfernen oder Löschen von Systemen
        entries:
        - title: Fügen Sie ein vorhandenes System hinzu
          url: "/task-adding-systems.html"
        - title: Entfernen Sie eine Arbeitsumgebung
          url: "/task-removing.html"
        - title: Löschen Sie ein System
          url: "/task-deleting-working-env.html"
      - title: AWS Administration
        flavor: aws
        entries:
        - title: EC2 Instanztyp ändern
          url: "/task-change-ec2-instance.html"
        - title: Ändern Sie die Routingtabellen für HA-Paare
          url: "/task-change-route-tables.html"
        - title: Überwachung der AWS-Kosten
          url: "/task-monitoring-costs.html"
      - title: Azure-Administration
        flavor: azure
        entries:
        - title: Ändern Sie den Azure VM-Typ
          url: "/task-change-azure-vm.html"
        - title: CIFS-Sperren überschreiben
          url: "/task-overriding-cifs-locks.html"
        - title: Nutzen Sie einen Azure Private Link oder einen Service-Endpunkt
          url: "/task-enabling-private-link.html"
        - title: Verschieben von Ressourcengruppen
          url: "/task-moving-resource-groups-azure.html"
      - title: Google Cloud-Administration
        flavor: gcp
        entries:
        - title: Maschinentyp ändern
          url: "/task-change-gcp-machine.html"
      - title: Administration über System Manager
        url: "/task-administer-advanced-view.html"
      - title: Administration aus der CLI
        url: "/task-connecting-to-otc.html"
    - title: Systemzustand und Ereignisse
      entries:
      - title: AutoSupport-Einrichtung überprüfen
        url: "/task-verify-autosupport.html"
      - title: EMS konfigurieren
        url: "/task-configure-ems.html"
  - title: Konzepte
    entries:
    - title: Lizenzierung
      url: "/concept-licensing.html"
    - title: Storage
      entries:
      - title: Client-Protokolle
        url: "/concept-client-protocols.html"
      - title: Festplatten und Aggregate
        url: "/concept-storage.html"
      - title: Elastische Volumes in AWS
        flavor: aws
        url: "/concept-aws-elastic-volumes.html"
      - title: Daten-Tiering
        url: "/concept-data-tiering.html"
      - title: Storage-Management
        url: "/concept-storage-management.html"
      - title: Schreibgeschwindigkeit
        url: "/concept-write-speed.html"
      - title: Flash Cache
        url: "/concept-flash-cache.html"
      - title: WORM-Storage
        url: "/concept-worm.html"
    - title: Hochverfügbarkeitspaare
      entries:
      - title: HA-Paare in AWS
        flavor: aws
        url: "/concept-ha.html"
      - title: HA-Paare in Azure
        flavor: azure
        url: "/concept-ha-azure.html"
      - title: HA-Paare in GCP
        flavor: gcp
        url: "/concept-ha-google-cloud.html"
      - title: Maßnahmen während der Storage-Übernahme
        url: "/concept-degraded-ha-pair.html"
    - title: Sicherheit
      url: "/concept-security.html"
    - title: Leistung
      url: "/concept-performance.html"
    - title: Management des Node-basierten BYOL
      url: "/concept-license-management.html"
    - title: AutoSupport und Active IQ Digital Advisor
      url: "/concept-active-iq.html"
    - title: Standardkonfigurationen
      url: "/reference-default-configs.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Weitere Informationen zu Cloud Volumes ONTAP
      url: concept-overview-cvo.html
    - title: Schnellstartanleitung für AWS
      url: task-getting-started-aws.html
      flavor: aws
    - title: Schnellstart für Azure
      url: task-getting-started-azure.html
      flavor: azure
    - title: Schnellstart für Google Cloud
      url: task-getting-started-gcp.html
      flavor: gcp
  - title: Lizenzierung
    links:
    - title: Übersicht über die Lizenzierung
      url: concept-licensing.html
    - title: Management kapazitätsbasierter Lizenzen
      url: task-manage-capacity-licenses.html
    - title: Nicht zugewiesene knotenbasierte Exchange-Lizenzen
      url: task-manage-node-licenses.html#exchange-unassigned-node-based-licenses
    - title: Managen Sie Keystone Flex-Abonnements
      url: task-manage-keystone.html
  - title: Storage-Management
    links:
    - title: Volumes erstellen
      url: task-create-volumes.html
    - title: Tiering inaktiver Daten in Objektspeicher
      url: task-tiering.html
    - title: Beschleunigter Datenzugriff mit FlexCache
      url: task-accelerate-data-access.html
    - title: ONTAP SAN-Host-Konfiguration
      url: https://docs.netapp.com/us-en/ontap-sanhost
  - title: Systemadministration
    links:
    - title: Upgrade von Cloud Volumes ONTAP
      url: task-updating-ontap-cloud.html
    - title: Stoppen und starten Sie Cloud Volumes ONTAP
      url: task-managing-state.html
  - title: Sicherheit
    links:
    - title: Verschlüsselung von Volumes mit NetApp Verschlüsselung
      url: task-encrypting-volumes.html
    - title: Ransomware-Schutz verbessern
      url: task-protecting-ransomware.html
  - title: API
    links:
    - title: Überblick über die Cloud Volumes ONTAP-API
      url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/overview.html
    - title: Die Verwendung der API wird vorbereitet
      url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/prepare.html
    - title: API-Referenz
      url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/api_ref_resources.html
  - title: Fehlerbehebung
    links:
    - title: NetApp Knowledge Base
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Volumes_ONTAP_(CVO)
  - title: Referenz
    links:
    - title: Unterstützte Konfigurationen
      url: https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html
    - title: Unterstützte Cloud-Regionen
      url: https://cloud.netapp.com/cloud-volumes-global-regions
    - title: Rechner
      url: https://cloud.netapp.com/calculator-hub
  - title: Blogs Community
    links:
    - title: NetApp Community
      url: https://community.netapp.com/t5/Cloud-Volumes-ONTAP/bd-p/CloudVolumes
    - title: Blog der BlueXP-Website
      url: https://cloud.netapp.com/blog/topic/cloud-volumes-ontap
    - title: Cloud-Webinare
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Alle BlueXP-Dokumentationen
