---
sidebar: sidebar 
permalink: task-manage-aggregates.html 
keywords: aggregates, delete aggregates, add disks, view aggregates 
summary: Managen Sie Aggregate selbst, indem Sie Festplatten hinzufügen, Informationen über die Aggregate anzeigen und sie löschen. 
---
= Management von Aggregaten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Managen Sie Aggregate selbst, indem Sie Festplatten hinzufügen, Informationen über die Aggregate anzeigen und sie löschen.


CAUTION: Alle Festplatten und Aggregate müssen direkt aus BlueXP erstellt und gelöscht werden. Sie sollten diese Aktionen nicht über ein anderes Management-Tool ausführen. Dies kann sich auf die Systemstabilität auswirken, die Fähigkeit zum Hinzufügen von Festplatten in der Zukunft beeinträchtigen und möglicherweise Kosten für redundante Cloud-Provider verursachen.

Wenn Sie ein Aggregat löschen möchten, müssen Sie zunächst die Volumes im Aggregat gelöscht haben.

Wenn einem Aggregat nicht mehr genügend Platz vorhanden ist, können Sie Volumes mit System Manager zu einem anderen Aggregat verschieben.

.Schritte
. Wählen Sie im linken Navigationsmenü die Option *Speicherung > Leinwand*.
. Doppelklicken Sie auf der leinwand-Seite auf die Cloud Volumes ONTAP Arbeitsumgebung, auf der Sie Aggregate verwalten möchten.
. Klicken Sie auf das Menü-Symbol und dann auf *Erweitert > Erweiterte Zuweisung*.
. Verwalten Sie Ihre Aggregate:
+
[cols="30,70"]
|===
| Aufgabe | Aktion 


| Anzeigen von Informationen zu einem Aggregat | Wählen Sie ein Aggregat aus und klicken Sie auf *Info*. 


| Erstellen Sie ein Volume auf einem bestimmten Aggregat | Wählen Sie ein Aggregat aus und klicken Sie auf *Create Volume*. 


| Hinzufügen von Festplatten zu einem Aggregat  a| 
.. Wählen Sie ein Aggregat aus und klicken Sie auf *Add Disks*.
.. Wählen Sie die Anzahl der Festplatten aus, die Sie hinzufügen möchten, und klicken Sie auf *Hinzufügen*.
+

TIP: Alle Festplatten in einem Aggregat müssen dieselbe Größe haben.



ifdef::aws[]



| Erhöhen Sie die Kapazität eines Aggregats, das Amazon EBS Elastic Volumes unterstützt  a| 
.. Wählen Sie ein Aggregat aus und klicken Sie auf *Kapazität erhöhen*.
.. Geben Sie die zusätzliche Kapazität ein, die Sie hinzufügen möchten, und klicken Sie dann auf *Hinzufügen*.
+
Beachten Sie, dass Sie die Kapazität des Aggregats um mindestens 256 gib oder 10 % der Aggregatgröße erhöhen müssen.

+
Wenn Sie beispielsweise ein 1.77 tib Aggregat haben, beträgt 10 % 181 gib. Das ist niedriger als 256 gib, daher muss die Größe des Aggregats um das Minimum von 256 gib erhöht werden.



endif::aws[]



| Löschen Sie ein Aggregat  a| 
.. Wählen Sie ein Aggregat aus, das keine Volumes enthält, und klicken Sie auf *Löschen*.
.. Klicken Sie zur Bestätigung erneut auf *Löschen*.


|===

